apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-user: YWJkZWxyaG1hbg==
  db-password: MTIzNDU2
  db-name: bWVybmRi
  cloudinary-cloud-name: ZHV2ZWY2a3Fq
  cloudinary-api-key: NTcxOTYyMTgzNDc0MzQz
  cloudinary-api-secret: b3JtR0UzMnVlMW4zZ0tHdWxDTndQeVZ1RGFz
  mongo-root-username: YWJkZWxyaG1hbg==
  mongo-root-password: MTIzNDU2
