{{- if .Values.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-user: {{ .Values.env.DB_USER | b64enc }}
  db-password: {{ .Values.env.DB_PASSWORD | b64enc }}
  cloudinary-cloud-name: {{ .Values.env.CLOUDINARY_CLOUD_NAME | b64enc }}
  cloudinary-api-key: {{ .Values.env.CLOUDINARY_API_KEY | b64enc }}
  cloudinary-api-secret: {{ .Values.env.CLOUDINARY_API_SECRET | b64enc }}
{{- end }}
