{{- if .Values.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-name: {{ .Values.env.DB_NAME | b64enc | quote }}
  db-user: {{ .Values.env.DB_USER | b64enc | quote }}
  db-password: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
  cloudinary-cloud-name: {{ .Values.env.CLOUDINARY_CLOUD_NAME | b64enc | quote }}
  cloudinary-api-key: {{ .Values.env.CLOUDINARY_API_KEY | b64enc | quote }}
  cloudinary-api-secret: {{ .Values.env.CLOUDINARY_API_SECRET | b64enc | quote }}
  mongo-root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
