apiVersion: v1
kind: Secret
metadata:
  name: mern-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-user: "${{ secrets.DB_USER }}"
  db-password: "${{ secrets.DB_PASSWORD }}"
  db-name: "${{ secrets.DB_NAME }}"
  cloudinary-cloud-name: "${{ secrets.CLOUDINARY_CLOUD_NAME }}"
  cloudinary-api-key: "${{ secrets.CLOUDINARY_API_KEY }}"
  cloudinary-api-secret: "${{ secrets.CLOUDINARY_API_SECRET }}"
  mongo-root-username: "${{ secrets.MONGO_ROOT_USERNAME }}"
  mongo-root-password: "${{ secrets.MONGO_ROOT_PASSWORD }}"

