server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Inject correct backend URL
    location /env.js {
        add_header Content-Type application/javascript;
        return 200 'window._env_ = { REACT_APP_SERVER_URL: "http://172.20.10.6:30500" };';
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}
