sonar.projectKey=abdelrhmanmohamed1234_End-to-End-GitOps-Deployment-For-Full-Stack-App
sonar.organization=abdelrhmanmohamed1234
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusion=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,build/**,coverage/**
