replicaCount: 3

image:
  repository: abdelrhmanmohamed1102002/mern-backend
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30500

env:
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "merndb"
  DB_USER: "abdelrhman"
  DB_PASSWORD: "123456"
  CLOUDINARY_CLOUD_NAME: "duvef6kqj"
  CLOUDINARY_API_KEY: "571962183474343"
  CLOUDINARY_API_SECRET: "ormGE32ue1n3gKGulCNwPyVuDas"

useSecret: false
persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "4.4"
  auth:
    rootUsername: abdelrhman
    rootPassword: "123456"
  service:
    port: 27017
  persistence:
    enabled: false

# ─── Autoscaling ──────────────────────────────────────────────
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
